version: "3.1"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  dotnet-1:
    build: 
      context: ./
    depends_on:
      - redis
    links:
      - redis
    ports: 
      - "5000:5000"    
    environment:
      - redisString=redis:6379
  dotnet-2:
    build:
      context: ./
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5001:5000"
    environment:
      - redisString=redis:6379